force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Logs requests and their response for the AWS Gateway callout.</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Integration Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Request_JSON__c.field-meta.xml
<CustomField>
    <fullName>Request_JSON__c</fullName>
    <description>Defines the request (in JSON format) that was sent during the callout.</description>
    <inlineHelpText>Defines the request (in JSON format) that was sent during the callout.</inlineHelpText>
    <label>Request JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Describes the number of retries after first failure.</description>
    <inlineHelpText>Describes the number of retries after first failure.</inlineHelpText>
    <label>Retry</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Defines the status of the returned response during the callout</description>
    <inlineHelpText>Defines the status of the returned response during the callout</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILURE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>Describes the status code for the response.</description>
    <inlineHelpText>Describes the status code for the response.</inlineHelpText>
    <label>Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Describes the Callout event name.</description>
    <inlineHelpText>Describes the Callout event name.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AML</fullName>
            </value>
            <value>
                <fullName>Person Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AWSCalloutBatch.cls
global class AWSCalloutBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return Database.getQueryLocator(
            'SELECT Id, Request_JSON__c, Status_Code__c, Status__c, Retry__c, Type__c FROM Integration_Log__c WHERE (Status_Code__c = 400 OR Status_Code__c = 401) AND Retry__c < 4 AND Type__c = \'AML\''
        );
    }
    
    global void execute(Database.BatchableContext bc, List<Integration_Log__c> scope){
        //create list of Ids to pass into the Future method callout
        List<Id> integrationLogIds = new List<Id>();
        
        // process each batch of records
        for(Integration_Log__c thisIntegrationLog : scope){
            System.debug('Callout from Batch');
            integrationLogIds.add(thisIntegrationLog.Id);
        }
        
        //check list size and call the Future method callout
        if(integrationLogIds.size() > 0){
            //send the request - Queueable JOB
        	System.enqueueJob(new AWSCalloutQueueable(integrationLogIds));
        }
    } 
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }    
}