force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Logs requests and their response for the AWS Gateway callout.</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Integration Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Request_JSON__c.field-meta.xml
<CustomField>
    <fullName>Request_JSON__c</fullName>
    <description>Defines the request (in JSON format) that was sent during the callout.</description>
    <inlineHelpText>Defines the request (in JSON format) that was sent during the callout.</inlineHelpText>
    <label>Request JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Describes the number of retries after first failure.</description>
    <inlineHelpText>Describes the number of retries after first failure.</inlineHelpText>
    <label>Retry</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Defines the status of the returned response during the callout</description>
    <inlineHelpText>Defines the status of the returned response during the callout</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILURE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>Describes the status code for the response.</description>
    <inlineHelpText>Describes the status code for the response.</inlineHelpText>
    <label>Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Describes the Callout event name.</description>
    <inlineHelpText>Describes the Callout event name.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AML</fullName>
            </value>
            <value>
                <fullName>Person Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AWSCalloutQueueable.cls
public class AWSCalloutQueueable implements Queueable, Database.AllowsCallouts {
    
    private List<Id> integrationLogIds;
    
    public AWSCalloutQueueable(List<Id> integrationLogIds){
        this.integrationLogIds = integrationLogIds;
    }
    public void execute(QueueableContext context) {
        //update records list
        List<Integration_Log__c> integrationLogsToUpdate = new List<Integration_Log__c>();
        //email records list
        List<Integration_Log__c> integrationLogsForEmail = new List<Integration_Log__c>();
        
        //get Integration Log record
        Map<Id, Integration_Log__c> allIntegrationLogRecordsMap = new Map<Id, Integration_Log__c>([SELECT Id, Request_JSON__c, Status_Code__c, Status__c, Retry__c, Type__c FROM Integration_Log__c WHERE Id IN :integrationLogIds]);
        
        //loop through the records
        for(Id thisIntegrationLogId : allIntegrationLogRecordsMap.keySet()){
            Integration_Log__c thisIntegrationLogRecord = allIntegrationLogRecordsMap.get(thisIntegrationLogId);
            //set http and send the request
            //set http request
            HttpRequest request = new HttpRequest();     
            request.setEndpoint('callout:aws_ingest/aml');
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            request.setBody((String)thisIntegrationLogRecord.Request_JSON__c);
            
            Http http = new Http();
            HttpResponse res = http.send(request);
            
            //check request response
            if(res.getStatusCode() == 202){
                
                //update Integration Log record to SUCCESS
                thisIntegrationLogRecord.Status__c = 'SUCCESS';
                thisIntegrationLogRecord.Status_Code__c = res.getStatusCode();
                integrationLogsToUpdate.add(thisIntegrationLogRecord);
                
            }else{   
                
                //update Integration Log record to FAILURE
                thisIntegrationLogRecord.Status__c = 'FAILURE';
                thisIntegrationLogRecord.Status_Code__c = res.getStatusCode();
                thisIntegrationLogRecord.Retry__c= thisIntegrationLogRecord.Retry__c+1;
                integrationLogsToUpdate.add(thisIntegrationLogRecord);
                
                //add integration logs that have retry = 4
                if(thisIntegrationLogRecord.Retry__c == 4){
                    integrationLogsForEmail.add(thisIntegrationLogRecord);
                }
                
            }
        }
        
        //update integration log records
        if(integrationLogsToUpdate.size() > 0){
           
            update integrationLogsToUpdate;
            
        }
        //send email
        if(integrationLogsForEmail.size() > 0){
            Messaging.SingleEmailMessage semail = new Messaging.SingleEmailMessage();
            String[] sendingTo = new String[]{'ramesh.odedra@trovemoney.co.nz'};
                semail.setToAddresses(sendingTo);
            semail.setSubject('Callout Results - Failed Retries');
            String plainTextBody = ' Hi there, ' + ' &nbsp; ';
            plainTextBody += 'Below described is/are the failed records: ';
            
            for(Integration_Log__c thisIntegrationLog : integrationLogsForEmail){
                plainTextBody += ' &nbsp; ';
                plainTextBody += 'Request String: ' + thisIntegrationLog.Request_JSON__c;
                plainTextBody += ' &nbsp; ';
                plainTextBody += 'Response Status: ' + thisIntegrationLog.Status__c;
                plainTextBody += ' &nbsp; ';
                plainTextBody += 'Request Status Code: ' + thisIntegrationLog.Status_Code__c;
                plainTextBody += ' &nbsp; ';
                plainTextBody += 'Number of tries: ' + (Integer)thisIntegrationLog.Retry__c;
            }
            
            plainTextBody += ' &nbsp; ';
            plainTextBody += ' Thank you! Regards, ';
            plainTextBody += ' &nbsp; ';
            plainTextBody += 'Automated Process';
            semail.setPlainTextBody(plainTextBody);
            if(!Test.isRunningTest()){
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] {semail});
            }
        }
    }
}