force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Logs requests and their response for the AWS Gateway callout.</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Integration Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Request_JSON__c.field-meta.xml
<CustomField>
    <fullName>Request_JSON__c</fullName>
    <description>Defines the request (in JSON format) that was sent during the callout.</description>
    <inlineHelpText>Defines the request (in JSON format) that was sent during the callout.</inlineHelpText>
    <label>Request JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Describes the Callout event name.</description>
    <inlineHelpText>Describes the Callout event name.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AML</fullName>
            </value>
            <value>
                <fullName>Person Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/Person_Detail_Change__e.object-meta.xml
<CustomObject>
    <description>This platform event is published when a person&apos;s details are changed.</description>
    <label>Person Detail Change</label>
    <pluralLabel>Person Detail Changes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Person_Detail_Change__e/fields/Account_Nickname__c.field-meta.xml
<CustomField>
    <fullName>Account_Nickname__c</fullName>
    <label>Account Nickname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Bank_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Number__c</fullName>
    <label>Bank Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Bank_Status__c.field-meta.xml
<CustomField>
    <fullName>Bank_Status__c</fullName>
    <label>Bank Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Defines the changed city of the person.</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Close_Request__c.field-meta.xml
<CustomField>
    <fullName>Close_Request__c</fullName>
    <label>Close Request</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Defines the changed country of the person account.</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <description>Defines the customer ID of the account.</description>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/ID_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>ID_Expiry_Date__c</fullName>
    <description>Expiry Date of the Passport</description>
    <label>ID Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/ID_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ID_First_Name__c</fullName>
    <label>ID First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/ID_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ID_Last_Name__c</fullName>
    <label>ID Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/ID_Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>ID_Middle_Name__c</fullName>
    <description>Generate data in the field to create a middle name Jason when CS change a middle name in SF.</description>
    <label>ID Middle Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/ID_Number__c.field-meta.xml
<CustomField>
    <fullName>ID_Number__c</fullName>
    <label>ID Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <description>ID Type: Drivers License or Passport</description>
    <label>ID Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/ID_Version__c.field-meta.xml
<CustomField>
    <fullName>ID_Version__c</fullName>
    <description>Version of the Drivers License</description>
    <label>ID Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/IRD_Number__c.field-meta.xml
<CustomField>
    <fullName>IRD_Number__c</fullName>
    <description>Defines the changed IRD number of the person.</description>
    <label>IRD Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <description>Defines the changed mobile number of the person.</description>
    <label>Mobile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Pause_Trading__c.field-meta.xml
<CustomField>
    <fullName>Pause_Trading__c</fullName>
    <label>Pause Trading</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/PIR__c.field-meta.xml
<CustomField>
    <fullName>PIR__c</fullName>
    <description>Defines the changed PIR of the person.</description>
    <label>PIR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Defines the changed postal code of the person.</description>
    <label>Postal Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Defines the changed street of the person.</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Suburb__c.field-meta.xml
<CustomField>
    <fullName>Suburb__c</fullName>
    <description>This field is mapped with the mailing city which has changed the label to Suburb.</description>
    <label>Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>Timestamp to overcome duplicate events</description>
    <label>Timestamp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Person Change Event</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AWSCallout.cls
public class AWSCallout
{ 
    public static String callAwsgateway(String customerId, String transactionId, Boolean Locked, Boolean Cloudcheckpass, Boolean PassedAML, Boolean pdsReceived)
    {
        //request body JSON
        JSONGenerator gen = JSON.createGenerator(true);    
        gen.writeStartObject();
        if (pdsReceived){
            gen.writeBooleanField('PDS_Received__c',pdsReceived);
            gen.writeStringField('Customer_ID__c', customerId);
        }
        else if(Locked == false && Locked!=null && PassedAML == False)
        {
            gen.writeBooleanField('Locked__c',Locked);
            gen.writeStringField('Customer_ID__c', customerId);
        }
         else if(PassedAML == True )
        {
            gen.writeBooleanField('Passed_AML__c',PassedAML);
            gen.writeStringField('Transaction_Id__c',transactionId);
            gen.writeStringField('Customer_ID__c', customerId);
        }
        
               
        //set JSON
        String jsonS = gen.getAsString();
        system.debug(jsonS);
        
        return jsonS;
    }  
    
    public static void personDetailsChangeCallout(List<Person_Detail_Change__e> listOfPersonDetailEvents){
        //Map of integration log data
        Map<String, String> integrationLogData = new Map<String, String>();
        //loop through event and generate JSON
        for(Person_Detail_Change__e thisEvent : listOfPersonDetailEvents){
            
            String jsonS = createJSON(thisEvent);
            
            //add the Id to integration log
            integrationLogData.put(jsonS, 'Person Details');            
        }
        
        if(integrationLogData.size() > 0){
            List<Id> integrationLogIds = initiateIntegrationLog(integrationLogData);
            //send the request - Queueable JOB
            System.enqueueJob(new AWSCalloutQueueable(integrationLogIds));
        }
    }

   
    
    public static List<Id> initiateIntegrationLog(Map<String, String> mapOfIntegrationsToInsert){
        List<Integration_Log__c> toInsertLogs = new List<Integration_Log__c>();
        List<Id> integrationLogIds = new List<Id>();
        for(String thisJSON : mapOfIntegrationsToInsert.keySet()){
            //Initialize an Integration Log record
            Integration_Log__c thisIntegrationLog = new Integration_Log__c();
            thisIntegrationLog.Request_JSON__c = thisJSON;
            thisIntegrationLog.Type__c = mapOfIntegrationsToInsert.get(thisJSON);
            toInsertLogs.add(thisIntegrationLog);   
        }
        //insert logs
        if(toInsertLogs.size() > 0){
            List<Database.SaveResult> srList = Database.insert(toInsertLogs);
            for(Database.SaveResult sr : srList){
                if(sr.isSuccess()){
                    integrationLogIds.add(sr.getId());
                }
            }
        }
        return integrationLogIds;
    }

    // Create JSON from Person Details Event 
    public static String createJSON(Person_Detail_Change__e thisEvent){
        //request body JSON
        JSONGenerator gen = JSON.createGenerator(true);    
        gen.writeStartObject();
        if(String.isNotEmpty(thisEvent.Customer_ID__c)){
            gen.writeStringField('Customer_ID__c', thisEvent.Customer_ID__c);
        }
        if(String.isNotEmpty(thisEvent.Type__c)){
            gen.writeStringField('Type__c', thisEvent.Type__c);
        }
        if(String.isNotEmpty(thisEvent.Mobile_Number__c)){
            gen.writeStringField('Mobile_Number__c', thisEvent.Mobile_Number__c);
        }
        if(String.isNotEmpty(thisEvent.PIR__c)){
            gen.writeStringField('PIR__c', thisEvent.PIR__c);
        }
        if(String.isNotEmpty(thisEvent.IRD_Number__c)){
            gen.writeStringField('IRD_Number__c', thisEvent.IRD_Number__c);
        }
        if(String.isNotEmpty(thisEvent.Street__c)){
            gen.writeStringField('Street__c', thisEvent.Street__c);
        }
        if(String.isNotEmpty(thisEvent.Suburb__c)){
            gen.writeStringField('Suburb__c', thisEvent.Suburb__c);
        }
        if(String.isNotEmpty(thisEvent.City__c)){
            gen.writeStringField('City__c', thisEvent.City__c);
        }
        if(String.isNotEmpty(thisEvent.Country__c)){
            gen.writeStringField('Country__c', thisEvent.Country__c);
        }
        if(thisEvent.Postal_Code__c != null){
            gen.writeNumberField('Postal_Code__c', Integer.valueOf(thisEvent.Postal_Code__c));
        }
        if(String.isNotEmpty(thisEvent.First_Name__c)){
            gen.writeStringField('First_Name__c', thisEvent.First_Name__c);
        }
        if(String.isNotEmpty(thisEvent.Last_Name__c)){
            gen.writeStringField('Last_Name__c', thisEvent.Last_Name__c);
        }
         if(String.isNotEmpty(thisEvent.Bank_Name__c)){
            gen.writeStringField('Bank_Name__c', thisEvent.Bank_Name__c);
        }
         if(String.isNotEmpty(thisEvent.Bank_Number__c)){
            gen.writeStringField('Bank_Number__c', thisEvent.Bank_Number__c);
        }
        if(String.isNotEmpty(thisEvent.Account_Nickname__c)){
            gen.writeStringField('Account_Nickname__c', thisEvent.Account_Nickname__c);
        }
        if(String.isNotEmpty(thisEvent.Bank_Status__c)){
            gen.writeStringField('Bank_Status__c', thisEvent.Bank_Status__c);
        }  
        if(String.isNotEmpty(thisEvent.Close_Request__c)){
            gen.writeStringField('Close_Request__c', thisEvent.Close_Request__c);
        }   
        if(String.isNotEmpty(thisEvent.ID_Type__c)){
            gen.writeStringField('ID_Type__c', thisEvent.ID_Type__c);
        } 
        if(String.isNotEmpty(thisEvent.ID_Number__c)){
            gen.writeStringField('ID_Number__c', thisEvent.ID_Number__c);
        } 
        if(String.isNotEmpty(String.valueOf(thisEvent.ID_Expiry_Date__c))){
            gen.writeStringField('ID_Expiry_Date__c', String.valueOf(thisEvent.ID_Expiry_Date__c));
        } 
        if(String.isNotEmpty(thisEvent.ID_Version__c)){
            gen.writeStringField('ID_Version__c', thisEvent.ID_Version__c);
        }  
        if(String.isNotEmpty(String.valueOf(thisEvent.Birthdate__c))){
            gen.writeStringField('Birthdate__c', String.valueOf(thisEvent.Birthdate__c));
        }
        if(String.isNotEmpty(thisEvent.ID_First_Name__c)){
            gen.writeStringField('ID_First_Name__c', thisEvent.ID_First_Name__c);
        }
        if(String.isNotEmpty(thisEvent.ID_Middle_Name__c)){
            gen.writeStringField('ID_Middle_Name__c', thisEvent.ID_Middle_Name__c);
        }
        if(String.isNotEmpty(thisEvent.ID_Last_Name__c)){
            gen.writeStringField('ID_Last_Name__c', thisEvent.ID_Last_Name__c);
        }
        if(String.isNotEmpty(thisEvent.Pause_Trading__c)){
            gen.writeStringField('Pause_Trading__c', thisEvent.Pause_Trading__c);
        }
        if(String.isNotEmpty(thisEvent.Timestamp__c)){
            gen.writeStringField('Timestamp__c', thisEvent.Timestamp__c);
        }
        //set JSON
        String jsonS = gen.getAsString();
        system.debug(jsonS);

        return jsonS;
    }
     

}