force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Logs requests and their response for the AWS Gateway callout.</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Integration Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Request_JSON__c.field-meta.xml
<CustomField>
    <fullName>Request_JSON__c</fullName>
    <description>Defines the request (in JSON format) that was sent during the callout.</description>
    <inlineHelpText>Defines the request (in JSON format) that was sent during the callout.</inlineHelpText>
    <label>Request JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Describes the number of retries after first failure.</description>
    <inlineHelpText>Describes the number of retries after first failure.</inlineHelpText>
    <label>Retry</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Defines the status of the returned response during the callout</description>
    <inlineHelpText>Defines the status of the returned response during the callout</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILURE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>Describes the status code for the response.</description>
    <inlineHelpText>Describes the status code for the response.</inlineHelpText>
    <label>Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Describes the Callout event name.</description>
    <inlineHelpText>Describes the Callout event name.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AML</fullName>
            </value>
            <value>
                <fullName>Person Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AWSCalloutTestClass.cls
@isTest
public class AWSCalloutTestClass {
    //true callout
    @isTest static void testAWSPostCallout() {
        Test.startTest();
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.Class, new AWSCalloutMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        AWSCallout.callAwsgateway('12345','12345',true, true, true, false);
        //stop test
        Test.stopTest();
    }
    
    //true callout
    @isTest static void testAWSAMLAndNoIDCallout() {
        Test.startTest();
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.Class, new AWSCalloutMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        AWSCallout.callAwsgateway('12345','12345',false, false, false, false);
        //stop test
        Test.stopTest();
    }
    
    //true callout
    @isTest static void testAWSCloudPassORAMLAndNoIDCallout() {
        Test.startTest();
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.Class, new AWSCalloutMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        AWSCallout.callAwsgateway('12345','12345',false, true, false, false);
        //stop test
        Test.stopTest();
    }
    
    //true callout
    @isTest static void testAWSPostLockedFalseCallout() {
        Test.startTest();
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.Class, new AWSCalloutMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        AWSCallout.callAwsgateway('12345','12345',false, false, false, false);
        //stop test
        Test.stopTest();
    }
    
    //false callout
    @isTest static void testAWSPostErrorCallout() {
        Test.startTest();
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.Class, new AWSCalloutMockFaillure()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        AWSCallout.callAwsgateway('12345','12345',true, true, true, false);
        //stop test
        Test.stopTest();
    }

    //false callout
    @isTest static void testAWSPostPDSReceived() {
        Test.startTest();
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.Class, new AWSCalloutMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        AWSCallout.callAwsgateway('12345','12345',false, false, false, true);
        //stop test
        Test.stopTest();
    }
    
    //test Batch
    @isTest static void testAWSCalloutBatch(){
        //create Few Records
        createFewIntegrationLogRecords(5);
        // after the testing stops, assert records were updated properly
        System.assertEquals(5, [SELECT COUNT() FROM Integration_Log__c WHERE (Status_Code__c = 400 OR Status_Code__c = 401) AND Retry__c < 4 AND Type__c = 'AML']);
        //start test
        Test.startTest();
        // callbatch class 
        AWSCalloutBatch awsCalloutBatch = new AWSCalloutBatch();
        Database.executeBatch(awsCalloutBatch);
        //callout mock
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.Class, new AWSCalloutMock()); 
        //stop test
        Test.stopTest();
        // after the testing stops, assert records were updated properly
        System.assertEquals(0, [SELECT COUNT() FROM Integration_Log__c WHERE (Status_Code__c = 400 OR Status_Code__c = 401) AND Retry__c < 4 AND Type__c = 'AML']);
        
    }
    
    //test Batch
    @isTest static void testAWSCalloutBatchFailure(){
        //create Few Records
        createFewIntegrationLogRecords(5);
        // after the testing stops, assert records were updated properly
        System.assertEquals(5, [SELECT COUNT() FROM Integration_Log__c WHERE (Status_Code__c = 400 OR Status_Code__c = 401) AND Retry__c < 4 AND Type__c = 'AML']);
        //start test
        Test.startTest();
        // callbatch class 
        AWSCalloutBatch awsCalloutBatch = new AWSCalloutBatch();
        Database.executeBatch(awsCalloutBatch);
        //callout mock
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.Class, new AWSCalloutMockFaillure()); 
        //stop test
        Test.stopTest();
        // after the testing stops, assert records were updated properly
        System.assertEquals(0, [SELECT COUNT() FROM Integration_Log__c WHERE (Status_Code__c = 400 OR Status_Code__c = 401) AND Retry__c < 4 AND Type__c = 'AML']);
        
    }
    
    @isTest static void testAWSCalloutSchedule(){
        Test.startTest();
        // Schedule the test job
        String yearThis = String.valueOf(Date.today().addYears(1).year());
        String jobId = System.schedule('ScheduledApexTest',
            '0 0 0 15 3 ? ' + yearThis, 
            new AWSCalloutSchedular());         
        // Stopping the test will run the job synchronously
        Test.stopTest();
    }
    
    
    public static void createFewIntegrationLogRecords(Integer numberOfRecords){
        List<Integration_Log__c> integrationLogsToInsert = new List<Integration_Log__c>();
        for(Integer i=0; i<numberOfRecords; i++){
            //request body JSON
            JSONGenerator gen = JSON.createGenerator(true);    
            gen.writeStartObject();
            gen.writeStringField('Customer_ID__c', '123' + i);
            gen.writeStringField('On_Boarding_ID__c', '123' + i);
            gen.writeStringField('Transaction_Id__c', '123' + i);
            gen.writeBooleanField('Locked__c', false);
            gen.writeBooleanField('Passed_AML__c', true);
            Integration_Log__c thisIntegrationLog = new Integration_Log__c();
            thisIntegrationLog.Request_JSON__c = gen.getAsString();
            thisIntegrationLog.Retry__c = 3;
            thisIntegrationLog.Status_Code__c = 401;
            thisIntegrationLog.Status__c = 'FAILURE';
            thisIntegrationLog.Type__c = 'AML';
            integrationLogsToInsert.add(thisIntegrationLog);
        }
        
        if(integrationLogsToInsert.size() > 0){
            insert integrationLogsToInsert;
        }
    }
}