force-app/main/default/objects/AcctUnlocked__e/AcctUnlocked__e.object-meta.xml
<CustomObject>
    <description>This event will be generated when either a cloudcheck pass for an account or an account unlocked by customer service representative</description>
    <label>Account Event</label>
    <pluralLabel>Account Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/AcctUnlocked__e/fields/Cloudcheck_Pass__c.field-meta.xml
<CustomField>
    <fullName>Cloudcheck_Pass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cloudcheck Pass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AcctUnlocked__e/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctUnlocked__e/fields/Locked__c.field-meta.xml
<CustomField>
    <fullName>Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AcctUnlocked__e/fields/NoID_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>NoID_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NoID Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AcctUnlocked__e/fields/Passed_AML__c.field-meta.xml
<CustomField>
    <fullName>Passed_AML__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passed AML</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AcctUnlocked__e/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>ID od the transaction that has been passed AML decision.</description>
    <label>Transaction Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/Person_Detail_Change__e.object-meta.xml
<CustomObject>
    <description>This platform event is published when a person&apos;s details are changed.</description>
    <label>Person Detail Change</label>
    <pluralLabel>Person Detail Changes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Person_Detail_Change__e/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Defines the changed city of the person.</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Defines the changed country of the person account.</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <description>Defines the customer ID of the account.</description>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/IRD_Number__c.field-meta.xml
<CustomField>
    <fullName>IRD_Number__c</fullName>
    <description>Defines the changed IRD number of the person.</description>
    <label>IRD Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <description>Defines the changed mobile number of the person.</description>
    <label>Mobile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/PIR__c.field-meta.xml
<CustomField>
    <fullName>PIR__c</fullName>
    <description>Defines the changed PIR of the person.</description>
    <label>PIR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Defines the changed postal code of the person.</description>
    <label>Postal Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Defines the changed street of the person.</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person_Detail_Change__e/fields/Suburb__c.field-meta.xml
<CustomField>
    <fullName>Suburb__c</fullName>
    <description>This field is mapped with the mailing city which has changed the label to Suburb.</description>
    <label>Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AWSTriggerTestClass.cls
@isTest
public class AWSTriggerTestClass {
    @isTest static void testEvent(){
        //init platform event
        AcctUnlocked__e amlEvent = new AcctUnlocked__e(Customer_ID__c = '12345',Transaction_Id__c='12345',Passed_AML__c = true, Locked__c = true, cloudcheck_pass__c = true, NoID_Email_Sent__c = true);
        
        //Test
        Test.startTest();
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.Class, new AWSCalloutMock()); 
        Database.SaveResult sr = EventBus.publish(amlEvent);            
        Test.stopTest();
                
        // Perform validations here
        // Verify SaveResult value
        System.assertEquals(true, sr.isSuccess());
    }
    
    @isTest static void testPersonDetailChangeEvent(){
        //init platform event
        Person_Detail_Change__e personDetailChange = new Person_Detail_Change__e();
        personDetailChange.Customer_ID__c = '12345';
        personDetailChange.First_Name__c = 'First Name change';
        personDetailChange.Last_Name__c = 'Last Name change';
        //personDetailChange.Salutation__c = 'Salutation Name change';
        //personDetailChange.Email__c = 'Email address change';
        personDetailChange.IRD_Number__c = '111';
        personDetailChange.City__c = 'Wellington';
        personDetailChange.Country__c = 'New Zealand';
        personDetailChange.Mobile_Number__c = '12345689'; 
        personDetailChange.PIR__c = '345';
        personDetailChange.Postal_Code__c = 1234;
        //personDetailChange.Salary__c = 1243;
        personDetailChange.Suburb__c = 'Wellington';
        personDetailChange.Street__c = 'Te Aro'; 
        
        
        //Test
        Test.startTest();
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.Class, new AWSCalloutMock()); 
        Database.SaveResult sr = EventBus.publish(personDetailChange);            
        Test.stopTest();
                
        // Perform validations here
        // Verify SaveResult value
        System.assertEquals(true, sr.isSuccess());
    }
    
    /*@isTest static void testInvalidEvent(){
        //init platform event
        AcctUnlocked__e amlEvent = new AcctUnlocked__e(Customer_ID__c = '12345');
        
        //Test
        Test.startTest();
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.Class, new AWSCalloutMock()); 
        Database.SaveResult sr = EventBus.publish(amlEvent);            
        Test.stopTest();
                
        // Perform validations here
        // Verify SaveResult value
        System.assertEquals(false, sr.isSuccess());
    }*/
}